### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by asfolcini** [BrainstemStudio/sparkpostphpcurl#1]
Is it possible to add the template use ?

`		
public function template($template){
    $this->msg['template'] = 'ohf-general';
}
`

I did not check if the 'template' should be specified inside the msg var.

thank you

**Comment by BrainstemStudio** [comment]
Hi There,

I added a template method into the API and added an example.  You will need to use the template function with your "template_id" and "substitution_data".  We ran tests and appears to work correctly.

Just a Note:
We are unlikely to build further changes as we only built this for lightweight use in our platform that handles e-mail templates locally (so we don't need templates from sparkpost).  But we updated this git with templates as R&D into SparkPost's API
